### ISSUE TITLE
Enhancement request: OAuth with Github to scan repos for Access Keys

### ISSUE THREAD

**Issue by mikeatlas** [cloudsploit/scans#10]
This is even something I'd consider building myself / adding to the project. Even secure keys on AWS can be insecure and exposed on a public github repo (even in deleted commit histories). Any interest?

**Comment by mikeatlas** [comment]
There's also the potential to actively scan https://api.github.com/events while running (or as part of a premium service) for leaked keys.

**Comment by matthewdfuller** [comment]
This is a really awesome idea. I'm trying to think through some logistics, but I imagine by using OAuth, we could just scan the user's public repos (or even private for a less severe warning) for known keys from their accounts. Hitting /events may be a bit resource intensive (although I have seen scripts out there that do something similar).

**Comment by mikeatlas** [comment]
It's actually real-world, not pointing fingers but I've indirectly been bit by this problem twice now (users pushing their `.bashrc` or `.zshrc` profiles and config settings.

**Comment by mikeatlas** [comment]
Well, even hitting private repos (organizations can have 100s, plus 100s of users with public non-org repos) with all git history commits to scan.... it's definitely intensive even at a small scale.

**Comment by mikeatlas** [comment]
Quick search by hand even yielded a key:
https://github.com/yukiyasunasu/pinroom/blob/25316c25e041661533734ef4b3432e5841b831e5/.env

**Comment by matthewdfuller** [comment]
Agreed, it's well beyond the scale of the existing scans, so I'm going to have to think on this one in order to fit it into the setup of the existing plugins. Perhaps GitHub offers a search API which could be hit directly on behalf of a user and include history, deleted files, etc. There was a hacker news thread once on GitHub searches for locating all sorts of things (SSH keys, AWS access keys, etc.). Will try to find it.

**Comment by mikeatlas** [comment]
I recall that HN posting as well but can't find that repo quickly either. https://github.com/michenriksen/gitrob maybe?

**Comment by mikeatlas** [comment]
yeah I think this is it it... gluing these two projects together would be magical - the utput of potential sensitive keys from cloudsploit-scan is compared with output of gitrob scan.

**Comment by mikeatlas** [comment]
Played around with `gitrob` internally. It's a nice tool but the author has not accepted PRs or bugfixes in nearly 7-8 months. Consider abandonware, I'd recommend you fork and salvage useful bits for iterating Github repos and source code and ditch the rest rather than try to integrate. It comes with a large singleton (for the most part) class that could be picked apart without a lot of struggles.

Gitrob also flags a lot of odd false-positives, combining this code with CloudSploit might really want to focus on using the iteration + oauth features from `gitrob` and narrow them down to look for AWS-specific matches.

**Comment by mikeatlas** [comment]
I also wrapped it in a Dockerized container if you want to try it out with potentially less setup:

https://github.com/weftio/weft-gitrob

**Comment by matthewdfuller** [comment]
Thanks for locating these projects, they'll be useful in doing something similar here. I took a look at we could do a combination of Oauth and GitHub search: https://developer.github.com/v3/search/

The only issue is, it's rate limited to 30 searches per minute, so accounts with large numbers of keys may take awhile to complete.

Also, AWS does not allow you to retrieve the secrets, so we may wind up with a lot of false positives (user hard-coded the access key, but not the secret).

**Comment by mikeatlas** [comment]
Well, general good practice policiies are that _all_ keys (including access keys) are considered secrets and belong in the `.env` file that that file is in `.gitignore` always, and they're kept out of source code.

I wonder... with the IAM SKD, could you just use

http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Types/ListUsersRequest.html combined with 
http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM/Client.html#list_access_keys-instance_method

Wouldn't matter if the secret keys were in github or not, but of they're both there or neither of them are there.

**Comment by tleyden** [comment]
I've been working on a project called [keynuker](https://github.com/tleyden/keynuker) that is *really* similar to what @mikeatlas described.  It uses the github events API and pretty much the exact AWS SDK calls described.

**Comment by mikeatlas** [comment]
Revivalist @tleyden takes a post from 2yr ago and turns it into a project!
