### ISSUE TITLE
sqs.getQueueAttributes fails when queue does not have SSE enabled

### ISSUE THREAD

**Issue by cmoore-cimpress** [cloudsploit/scans#102]
https://github.com/cloudsploit/scans/blob/924444b979b3f6298462c7eb13dc962cc28546dd/collectors/sqs/getQueueAttributes.js#L15

We are observing an issue where the SQS plugin returns UNKNOWN for queues that don't have server-side encryption enabled, even when performing the "Cross Account Access" check.

I suspect it is because the `KmsMasterKeyId` attribute of the `getQueueAttributes` API call is not allowed on queues without SSE. Using the aws cli, for example, I get error:

> An error occurred (InvalidAttributeName) when calling the GetQueueAttributes operation: Unknown Attribute KmsMasterKeyId

**Comment by matthewdfuller** [comment]
This should now be resolved with https://github.com/cloudsploit/scans/commit/5a5accb8f25034be4f76b4d947a1dfaee710430f
