### ISSUE TITLE
SSM reporting only on the first 10 parameters per region

### ISSUE THREAD

**Issue by dautremontb** [cloudsploit/scans#147]
When running cloudsploit we are only getting the first 10 SSM parameters per region.

aws --version
aws-cli/1.11.133 Python/2.7.5 Linux/3.10.0-693.11.6.el7.x86_64 botocore/1.6.0

pip freeze
Arpeggio==1.9.0
attrs==18.2.0
awscli==1.11.133
AWSScout2==3.2.1
Babel==0.9.6
backports.ssl-match-hostname==3.5.0.1
boto==2.45.0
boto3==1.4.6
botocore==1.6.0
certifi==2018.8.24
chardet==2.2.1
cloud-init==0.7.9
colorama==0.3.2
configobj==4.7.2
cov-core==1.15.0
coverage==3.6b3
decorator==3.4.0
docutils==0.11
enum34==1.1.6
ethtool==0.8
futures==3.0.5
iampoliciesgonewild==1.0.6.2
iniparse==0.4
invoke==1.2.0
ipaddress==1.0.16
IPy==0.75
Jinja2==2.7.2
jmespath==0.9.0
jsonpatch==1.2
jsonpointer==1.9
kitchen==1.1.1
lockfile==0.9.1
lxml==3.2.1
M2Crypto==0.21.1
Magic-file-extensions==0.2
MarkupSafe==0.11
netaddr==0.7.5
nose==1.3.7
nose2==0.6.5
opinel==3.3.4
parver==0.1.1
pciutils==1.7.3
perf==0.1
Pillow==2.0.0
pipenv==2018.7.1
policycoreutils-default-encoding==0.1
prettytable==0.7.2
pyasn1==0.1.9
pycurl==7.19.0
pygobject==3.22.0
pygpgme==0.3
pyinotify==0.9.4
pyjq==2.2.0
pyliblzma==0.5.3
pyOpenSSL==0.13.1
pyserial==2.6
pystache==0.5.3
python-daemon==1.6
python-dateutil==1.5
python-dmidecode==3.10.13
python-linux-procfs==0.4.9
pyudev==0.15
pyxattr==0.5.1
PyYAML==4.1
requests==2.6.0
rhnlib==2.5.65
rsa==3.4.1
s3transfer==0.1.10
schedutils==0.4
seobject==0.1
sepolicy==1.1
setuptools-scm==3.1.0
simplejson==3.10.0
six==1.11.0
subscription-manager==1.20.11
typing==3.6.6
uritools==2.2.0
urlgrabber==3.10
urllib3==1.10.2
virtualenv==16.1.0.dev0
virtualenv-clone==0.3.0
yum-metadata-parser==1.1.4

**Comment by kallu** [comment]
This due to pagination in AWS API response. Currently collector does support paginated results. However you can try to mitigate the issue by increasing MaxResults from default 10 up to 50 (max. supported by SSM API). To do this, add "params" setting into SSM in collect.js

	SSM: {
		describeParameters: {
			property: 'Parameters'
			params: {
				MaxResults: 50
			}
		}
	},

**Comment by matthewdfuller** [comment]
@dautremontb - I've made the change that @kallu suggested via [this commit](https://github.com/cloudsploit/scans/commit/2eb152a1c16eaf6a831b7cb50f1bfc156d1cd746). As he mentioned, the long-term option is to add pagination support to the collector, which is in the works, but a bit more complex than the above change.

**Comment by matthewdfuller** [comment]
Apologies for the lack of update on this ticket - we actually deployed a fix quite a bit ago. You can see the [new pagination parameters for SSM here](https://github.com/cloudsploit/scans/blob/7f9135076e5ef254ff375f96092567ddca7a8830/collectors/aws/collector.js#L412-L419).
