### ISSUE TITLE
azure plugins storageaccounts and storageAccounts

### ISSUE THREAD

**Issue by w500** [cloudsploit/scans#151]
Hello,

Are there meant to be two storageaccounts directories in the azure dir?

https://github.com/cloudsploit/scans/tree/master/plugins/azure

When I run CloudSploit I can a azure module error referring to storageAccountsEncryption.js

Is it due to the two storageaccounts  - when there should be one?

Thanks

**Comment by matthewdfuller** [comment]
Hi @w500 - this should now be fixed as we have standardized on a lowercase naming for those plugins. Are you able to confirm?

**Comment by w500** [comment]
Thank you. Yes I confirm it runs good.
