### ISSUE TITLE
The Firehose delivery stream does not use a KMS key for SSE

### ISSUE THREAD

**Issue by mrahman4** [cloudsploit/scans#158]
Although I enabled the Encryption in firehose stream, scan still gives me failure in firehose "The Firehose delivery stream does not use a KMS key for SSE"
Can anyone help me in this?

**Comment by matthewdfuller** [comment]
Hi @mrahman4 - I believe you may have been encountering this issue if your Firehose stream does not have an [S3 destination](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Firehose.html#describeDeliveryStream-property). We've pushed a [new commit](https://github.com/cloudsploit/scans/commit/ef4b82ea822bf2a68f40b9405923ad277d1cce19) that may solve your issue. Could you try a re-scan and let me know?

**Comment by mrahman4** [comment]
Yes Its working now :)
