### ISSUE TITLE
AWS Configuration Recorder Status False Positive - "Pending"

### ISSUE THREAD

**Issue by connor-tyndall** [cloudsploit/scans#170]
https://github.com/cloudsploit/scans/blob/master/plugins/aws/configservice/configServiceEnabled.js#L66

This scan that checks if AWS Config is recording and properly delivering will deliver the warning message `Config Service is configured, and recording, but not delivering properly` if the lastStatus message returns "Pending". This seems to be a timing issue where it catches it when it is pending delivery. 

According to AWS, the ConfigurationRecordersStatus will return "Pending" when the recorder has started and will return "Success" or "Failed". 

We are getting notified when this scan returns "WARN" because it returned a "Pending" status. 

Can logic be added to this scan to account for this status in case the scan happens to run when the recorder is currently running?

**Comment by matthewdfuller** [comment]
Hi @connor-tyndall - thank you for reporting. In the same code, a few lines up, I see: https://github.com/cloudsploit/scans/blob/master/plugins/aws/configservice/configServiceEnabled.js#L61 which should look for ` crs.lastStatus == 'PENDING'` as well. I wonder if it's a case-sensitivity issue. If so, `crs.lastStatus.toUpperCase() == 'PENDING'` should fix it. I'll take a look.

**Comment by matthewdfuller** [comment]
I believe [this commit](https://github.com/cloudsploit/scans/commit/11caf0948e5baae1660038b7722d0a4dec0a41cf#diff-aa822dd1385353ea870be2a66d334e1fL61) fixes this issue. Could you kindly confirm your results as well?

**Comment by matthewdfuller** [comment]
Going to close this issue; please re-open if you see further invalid results.
