### ISSUE TITLE
Plugin for AWS Shield Advanced

### ISSUE THREAD

**Issue by jcornell123** [cloudsploit/scans#178]
We would like some plugins related to Shield Advanced.

- Subscription Enabled - CLI Command: aws shield get-subscription-state
- Emergency Contacts are set - CLI Command aws shield describe-emergency-contact-settings
- Protections Established - CLI Command aws shield list-protections

**Comment by matthewdfuller** [comment]
@jcornell123 - thanks for the recommendations. We've pushed 3 new plugins for the above. They'll be pulled into the SaaS shortly.

https://github.com/cloudsploit/scans/tree/master/plugins/aws/shield

**Comment by matthewdfuller** [comment]
Closing since plugins have been deployed.
