### ISSUE TITLE
monitoringMetrics does not match return values from AWS CLI

### ISSUE THREAD

**Issue by garretfick** [cloudsploit/scans#188]
monitoringMetrics.js looks for specific patters in order to match metrics. However, there are a number of patterns that do not match how the AWS CLI actually returns data. This causes false positives for failed best practices. Some of the patterns are clearly wrong - have extra quote or curly brace that would never be a valid pattern.

**Comment by garretfick** [comment]
I have a fix for this that I should be able to publish on Monday

**Comment by garretfick** [comment]
See https://github.com/cloudsploit/scans/pull/189 for the proposed fix

**Comment by matthewdfuller** [comment]
Thanks @garretfick - #189 is merged now, so going to close this
