### ISSUE TITLE
Support Google Cloud Platform (GCP)

### ISSUE THREAD

**Issue by matthewdfuller** [cloudsploit/scans#191]
Based on user feedback, CloudSploit is prioritizing support for Google Cloud Platform as its next cloud (following the beta rollout of Azure, Oracle, and GitHub support).

We've begun the initial investigation required for authentication and collection interfaces, but are interested in community recommendations for an initial set of security checks and controls.

Please comment or vote on security checks for GCP that you would like to see.

**Comment by SyCode7** [comment]
Wow, that sounds really awesome. For a start, you can take a look at what the guys at [Forseti ](https://opensource.google.com/projects/forseti-security) have done so far. For examples here are some of the rules for security checks: [rules GitHub repo](https://github.com/forseti-security/forseti-security/tree/dev/rules).

**Comment by sandrom** [comment]
I am very happy to hear that!

**Comment by erzz** [comment]
Great news! Eagerly await (and willing to beta test!)

**Comment by matthewdfuller** [comment]
Hey folks! GCP support has been released, both here, as well as in the SaaS (see our [announcement post](https://blog.aquasec.com/aqua-cspm-google-cloud-security)). I'm going to close this issue but if you have any questions, please ping me directly.
