### ISSUE TITLE
Elasticsearch HTTPS Scan Produces False Negatives

### ISSUE THREAD

**Issue by chrisoverzero** [cloudsploit/scans#211]
The test for Elasticsearch HTTPS enforcement expects a response's `DomainStatus` key to have a value which includes the key `DomainEndpointOptions` (whose value further includes a key `EnforceHTTPS`). This is indeed the shape of data I get when using the AWS CLI:

```json
$ aws es describe-elasticsearch-domain --domain-name '<DOMAIN>' --query 'DomainStatus.DomainEndpointOptions'
{
    "EnforceHTTPS": true,
    "TLSSecurityPolicy": "Policy-Min-TLS-1-0-2019-07"
}
```

...but the shape of data returned by the API call in the scan is not (anonymized from "Live Run" Raw Response):

<details>
<summary>Long JSON blob</summary>
<pre>
"DomainStatus": {
  "DomainId": "[ACCOUNT]/[DOMAIN]",
  "DomainName": "[DOMAIN]",
  "ARN": "[ARN]",
  "Created": true,
  "Deleted": false,
  "Endpoint": "<ENDPOINT>",
  "Processing": false,
  "UpgradeProcessing": false,
  "ElasticsearchVersion": "6.7",
  "ElasticsearchClusterConfig": {
    "InstanceType": "r5.large.elasticsearch",
    "InstanceCount": 2,
    "DedicatedMasterEnabled": false,
    "ZoneAwarenessEnabled": true,
    "ZoneAwarenessConfig": {
      "AvailabilityZoneCount": 2
    },
    "DedicatedMasterType": null,
    "DedicatedMasterCount": null
  },
  "EBSOptions": {
    "EBSEnabled": true,
    "VolumeType": "gp2",
    "VolumeSize": 10,
    "Iops": null
  },
  "AccessPolicies": "",
  "SnapshotOptions": {
    "AutomatedSnapshotStartHour": 0
  },
  "CognitoOptions": {
    "Enabled": true,
    "UserPoolId": "[USER_POOL]",
    "IdentityPoolId": "[IDENTITY_POOL]",
    "RoleArn": "[ROLE]"
  },
  "EncryptionAtRestOptions": {
    "Enabled": true,
    "KmsKeyId": "[KEY]"
  },
  "NodeToNodeEncryptionOptions": {
    "Enabled": true
  },
  "AdvancedOptions": {
    "rest.action.multi.allow_explicit_index": "true"
  },
  "LogPublishingOptions": {
    "ES_APPLICATION_LOGS": {
      "CloudWatchLogsLogGroupArn": "[ARN]",
      "Enabled": true
    },
    "INDEX_SLOW_LOGS": {
      "CloudWatchLogsLogGroupArn": "[ARN]",
      "Enabled": true
    },
    "SEARCH_SLOW_LOGS": {
      "CloudWatchLogsLogGroupArn": "[ARN]",
      "Enabled": true
    }
  },
  "ServiceSoftwareOptions": {
    "CurrentVersion": "R20190927-P3",
    "NewVersion": "",
    "UpdateAvailable": false,
    "Cancellable": false,
    "UpdateStatus": "COMPLETED",
    "Description": "There is no software update available for this domain.",
    "AutomatedUpdateDate": "2019-11-13T07:56:14.000Z"
  }
}
</pre>
</details>

**Comment by matthewdfuller** [comment]
Hi @chrisoverzero - thanks for opening the issue. This should be resolved in the latest version; the issue was an out-of-date AWS SDK in the package.json file (needed to upgrade to get the new ES parameters).

**Comment by chrisoverzero** [comment]
I confirm. Great, thanks so much.
