### ISSUE TITLE
--json switch for JSON scan result not working

### ISSUE THREAD

**Issue by nx-jackal** [cloudsploit/scans#228]
Tried --csv is working but --json seems not implemented in postprocess/output.js

**Comment by ssteo** [comment]
Created a PR here https://github.com/cloudsploit/scans/pull/229

**Comment by dinvlad** [comment]
Looks like this has been reverted in d106029e210760269f0f166d59f080302123ad1e, could you please un-revert?

**Comment by nx-jackal** [comment]
Sorry @dinvlad  , what do you mean un-revert? There is no such options in https://github.com/cloudsploit/scans/pull/229 and it was merged earlier?

**Comment by dinvlad** [comment]
@nx-jackal Sorry, I meant it was implemented in #229, but then removed (perhaps accidentally) here: https://github.com/cloudsploit/scans/commit/43dd6784aa6ac7ac6842b18635c145ca3f6df9ea#diff-ae22b7994cdd4000a9df6434b7d7724bL311-L318 (scroll all the way down, and you'll see the following)
<img width="659" alt="Screen Shot 2020-03-27 at 11 15 19 PM" src="https://user-images.githubusercontent.com/137337/77813697-f5c9f680-7080-11ea-9c08-038e63589fe8.png">
