### ISSUE TITLE
Incomplete documentation about lambda function

### ISSUE THREAD

**Issue by pandeybk** [cloudsploit/scans#24]
I am trying to run this application using lambda function. My Lambda function API end points gives following output. Not sure what to do with this. Documentation on these things would be helpful.

> {
   "code":0,
   "data":{
      "plugins":[
         {
            "title":"CloudTrail Bucket Delete Policy",
            "query":"cloudtrailBucketDelete",
            "description":"Ensures CloudTrail logging bucket has a policy to prevent deletion of logs without an MFA token"
         },
         {
            "title":"CloudTrail Enabled",
            "query":"cloudtrailEnabled",
            "description":"Ensures CloudTrail is enabled for all regions within an account"
         },
         {
            "title":"Account Limits",
            "query":"accountLimits",
            "description":"Determine if the number of resources is close to the AWS per-account limit"
         },
         {
            "title":"Security Groups",
            "query":"securityGroups",
            "description":"Determine if sensitive ports are open to all source addresses"
         },
         {
            "title":"Certificate Expiry",
            "query":"certificateExpiry",
            "description":"Detect upcoming expiration of certificates used with ELBs"
         },
         {
            "title":"Insecure Ciphers",
            "query":"insecureCiphers",
            "description":"Detect use of insecure ciphers on ELBs"
         },
         {
            "title":"Password Policy",
            "query":"passwordPolicy",
            "description":"Ensures a strong password policy is setup for the account"
         },
         {
            "title":"Root Account Security",
            "query":"rootAccountSecurity",
            "description":"Ensures a multi-factor authentication device is enabled for the root account and that no access keys are present"
         },
         {
            "title":"Users MFA Enabled",
            "query":"usersMfaEnabled",
            "description":"Ensures a multi-factor authentication device is enabled for all users within the account"
         },
         {
            "title":"Access Keys",
            "query":"accessKeys",
            "description":"Ensures access keys are properly rotated and audited"
         },
         {
            "title":"Group Security",
            "query":"groupSecurity",
            "description":"Ensures groups contain users and policies"
         },
         {
            "title":"Detect EC2 Classic",
            "query":"detectClassic",
            "description":"Ensures AWS VPC is being used instead of EC2 Classic"
         },
         {
            "title":"S3 Buckets",
            "query":"s3Buckets",
            "description":"Ensures S3 buckets use proper policies and access controls"
         },
         {
            "title":"Domain Security",
            "query":"domainSecurity",
            "description":"Ensures domains are properly configured in Route53"
         },
         {
            "title":"Database Security",
            "query":"databaseSecurity",
            "description":"Ensures databases are properly configured in RDS"
         }
      ]
   }
}

**Comment by matthewdfuller** [comment]
Apologies for not having more documentation for this. I am pushing a commit now that includes detailed steps for getting it working.

**Comment by matthewdfuller** [comment]
See https://github.com/cloudsploit/scans#running-scans-via-lambda

**Comment by pandeybk** [comment]
This is perfect, I just tested and it works,

`curl -X POST <api_gateway_url> -d '{"plugins": []}' -H "x-api-key:secret_key"`
