### ISSUE TITLE
Security vulnerabilities in Google Kubernetes Cluster. 

### ISSUE THREAD

**Issue by kaushalshriyan** [cloudsploit/scans#242]
I am running the below command to find out security vulnerabilities in Google Kubernetes Cluster. 

```
node index.js --console --csv=./cloudsploitout.csv --ignore-ok --compliance=cis
node index.js --console --csv=./cloudsploitout.csv --ignore-ok --compliance=cis-1
node index.js --console --csv=./cloudsploitout.csv --ignore-ok --compliance=cis-2
```
The report does not mention the below vulnerabilities. 

<img width="557" alt="GKEVulnerabilities" src="https://user-images.githubusercontent.com/1860899/82238546-1f065500-9955-11ea-913e-03e7f6c03fb5.png">

Whereas when I click the scan button using https://cloud.aquasec.com/signin as per the below screenshot attached, it is reporting the above vulnerability.

<img width="1203" alt="Screenshot 2020-05-18 at 10 17 15 PM" src="https://user-images.githubusercontent.com/1860899/82238809-7c9aa180-9955-11ea-9275-79663cfc5636.png">
 
Do I need to enable any configuration or settings in the below command which is basically a self-hosted method?

```
node index.js --console --csv=./cloudsploitout.csv --ignore-ok --compliance=cis
node index.js --console --csv=./cloudsploitout.csv --ignore-ok --compliance=cis-1
node index.js --console --csv=./cloudsploitout.csv --ignore-ok --compliance=cis-2
``` 

Please suggest.

**Comment by kaushalshriyan** [comment]
Checking in again if someone can pitch in for help. I have not got any response to my earlier issues too.

**Comment by matthewdfuller** [comment]
Hi @kaushalshriyan - for support regarding the open source and hosted products and any differences between the two, we encourage you to open a ticket with our support team. There are a number of differences between these versions of the product, but unfortunately we cannot provide support here for those.
