### ISSUE TITLE
Callback errors after update

### ISSUE THREAD

**Issue by philcoxcoupa** [cloudsploit/scans#56]
I have been using the older version (last Dec)without and issue for a while. Did a pull to update, and now getting the following errors:

cloudsploit/scans/plugins/cloudtrail/cloudtrailBucketAccessLogging.js:66
			callback(null, results, source);
			^

TypeError: callback is not a function
    at /Users/philcox/src/cloudsploit/scans/plugins/cloudtrail/cloudtrailBucketAccessLogging.js:66:4
    at /Users/philcox/src/cloudsploit/scans/node_modules/async/dist/async.js:365:16
    at replenish (/Users/philcox/src/cloudsploit/scans/node_modules/async/dist/async.js:831:29)
    at /Users/philcox/src/cloudsploit/scans/node_modules/async/dist/async.js:842:29
    at /Users/philcox/src/cloudsploit/scans/node_modules/async/dist/async.js:804:16
    at /Users/philcox/src/cloudsploit/scans/plugins/cloudtrail/cloudtrailBucketAccessLogging.js:22:32
    at /Users/philcox/src/cloudsploit/scans/node_modules/async/dist/async.js:3339:20
    at replenish (/Users/philcox/src/cloudsploit/scans/node_modules/async/dist/async.js:836:21)
    at /Users/philcox/src/cloudsploit/scans/node_modules/async/dist/async.js:842:29
    at /Users/philcox/src/cloudsploit/scans/node_modules/async/dist/async.js:804:16

Any ideas?

For Ref: 
24e02360ce4c96e1009916bb35945be51cff69eb refs/remotes/origin/ap-south-1
525a34e21f4378571b3c5e8a590c019368446c4a refs/remotes/origin/master
1e0d307f1743bdb82ffbfcab74502989a54fe755 refs/remotes/origin/plugins-to-tests

**Comment by jkabhishek** [comment]
can you please update the fork again , and use master branch only

**Comment by matthewdfuller** [comment]
This should be resolved; please re-open if you see a reoccurrence.
