### ISSUE TITLE
which license?

### ISSUE THREAD

**Issue by kmcgrath** [cloudsploit/scans#8]
In package.json the license is 'ISC'.  The LICENSE file is GPLv3.  Which one is being used for the project?

**Comment by matthewdfuller** [comment]
Sorry for the confusion. The license should be GPLv3. I'll update the package file soon.

**Comment by kmcgrath** [comment]
Thank-you.  I have some existing modules I'd like to test as CloudSploit scans plugins.  Wanted to make sure I follow the correct license.

**Comment by matthewdfuller** [comment]
Fixed with a previous commit: 7d7168ef69
