### ISSUE TITLE
Support for Azure Scans

### ISSUE THREAD

**Issue by biswajitbehera** [cloudsploit/scans#97]
A similar structure/scan for Azure would be good.

**Comment by matthewdfuller** [comment]
@biswajitbehera - thank you for the feedback. We don't have any plans to share at the moment, but we're certainly considering Azure for future updates. If you have any existing scans, scripts, etc. that you'd be willing to share, we'd be happy to consider them.

**Comment by mittalnishant** [comment]
Hi Matt, Can you please add Azure integration as well ?
